name: Publish Image

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Login to Docker Hub
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build & Push - Latest
        run: |
          docker buildx build --push \
          -t fazalfarhan01/earnapp-earning-monitor:latest \
          -t fazalfarhan01/earnapp-earning-monitor:python-latest \
          -t fazalfarhan01/earnapp-earning-monitor:yariya-latest \
          -t fazalfarhan01/earnapp-earning-monitor:python-2.1.2 \
          --platform linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6 .

      - name: Update Docker Hub Readme
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: fazalfarhan01/earnapp-earning-monitor
          short-description: Watches your earnings on EarnApp and notifies you when you earned balance or received an payout.
          readme-filepath: README.md